### ISSUE TITLE
Error that doesn't show in errors.txt

### ISSUE THREAD

**Issue by G0dvv** [Cloudzik1337/DiscordUsernameChecker#4]
Right when it asks how many threads I want, it spams 
"sh: 1: title: not found" over and over again.

![Screen Shot 2023-12-17 at 9 18 22 AM](https://github.com/Cloudzik1337/DiscordUsernameChecker/assets/94789068/00b72011-2ffc-422a-b151-e5df1fc46ae6)

**Comment by Cloudzik1337** [comment]
Hi is what os you are using

**Comment by Cloudzik1337** [comment]
Pls tell mi if #5 fixes it

**Comment by G0dvv** [comment]
I am using replit on macOS Sonoma

**Comment by 8cf** [comment]
Thank you! I will see if it works

**Comment by Cloudzik1337** [comment]
> I am using replit on macOS Sonoma

Please replace cloud_checker.py with freshly downloaded one
